### PR TITLE
Omc3 gui

### PR DESCRIPTION
**Pull request by JoschD**
.. and more ...,

### CODE REVIEW

**Comment by fsoubelet** [comment]
TODO:
- @JoschD check the links
- @JoschD add bbgui default options information
- merge resources landing page (old resources page) into link for those not already there

**Comment by fsoubelet** [comment]
I've checked the links, here's those that didn't work for me

- [ ] All 3 `artifactory` links for GUIS
- [ ] The bblumi site
- [ ] AccPy wiki (requires to be on the CERN network maybe?)
- [ ] INCA and LSA Applications
- [ ] CERN CBNG Manual
- [ ] LSA Wiki
- [ ] Java Guidelines link

So that's pretty much all `wiki.cern.ch` links and a few more.

**Comment by JoschD** [comment]
> I've checked the links, here's those that didn't work for me
> 
> * [ ]  All 3 `artifactory` links for GUIs
> * [ ]  The bblumi site
> * [ ]  AccPy wiki
> * [ ]  INCA and LSA Applications wiki
> * [ ]  CERN CBNG Manual wiki
> * [ ]  LSA Wiki
> * [ ]  Java Guidelines link wiki
> 
> So that's pretty much all `wiki.cern.ch` links and a few more.

Did you change anything there? Because all work for me, apart from the java guidelines,
which are now `https://wikis.cern.ch/display/DEV/Java+development+guidelines`

BUT you have to be in the CERN network or use a proxy to access the wikis....

**Comment by fsoubelet** [comment]
> Did you change anything there? Because all work for me, apart from the java guidelines,
> which are now `https://wikis.cern.ch/display/DEV/Java+development+guidelines`
> 
> BUT you have to be in the CERN network or use a proxy to access the wikis....
> (see /tricks/#accessing-cern-internal-websites ;) )

Does that include also the `artifactory`

Can I let you change the link for the java guidelines?

**Review by fsoubelet — APPROVED** [review]

**Pull request merged**
