### PR TITLE
FAQ Section on BBsrc Outputs

### PR DESCRIPTION
**Pull request by fsoubelet**
A little bit of content on the naming meaning (`get_*.out`, `get_*_free.out`, `get_*_free2.out`) in the BBsrc output files.

I'm opening this PR right away as I want to have the information on the website and stop looking for it every time.

Site build available in the checks tab. Please proofread, adjustements welcome.

### CODE REVIEW

**Comment by awegsche** [comment]
I propose to link to https://technotes.bnl.gov/PDF?publicationId=25360 as reference for the analytical compensation method

**Comment by awegsche** [comment]
and since you ask "why various outputs":
- the "_free2" method sometimes is more robust (doesn't rely on the existence of certain BPMs in the output [after cleanin])
- for debugging purposes - if the final result looks unbelievable, it might be of advantage to check the uncompensated output to rule out (or confirm) a failure in the compensation
- for e.g. phase, both compensated and uncompensated values are calculated anyway, so why not dump them while we can?

**Comment by fsoubelet** [comment]
Updated. I am not sure what you mean by your third point exactly. Beta-Beat.src already outputs all cases for the phase values.

**Comment by awegsche** [comment]
> Updated. I am not sure what you mean by your third point exactly. Beta-Beat.src already outputs all cases for the phase values.

Well, it's to answer the question: "why do we output this at all?". But you can ignore this point for BetaBeat src. (in omc3 we should reintroduce this output, but that discussion doesn't belong here).

**Comment by awegsche** [comment]
For what it's worth, Ryoichi sent me a "draft" latex document explaining the compensation of phase, α, β and γ functions. maybe we could integrate this in our "Physics" section?

**Comment by fsoubelet** [comment]
> For what it's worth, Ryoichi sent me a "draft" latex document explaining the compensation of phase, α, β and γ functions. maybe we could integrate this in our "Physics" section?

In a different PR, why not.

**Review by awegsche — APPROVED** [review]
Looks super great. 

I have the impression that one *could* expand on this in the future but it's absolutely fine like this.

**Pull request merged**
